server:
  port: 8070

spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql
    username: 
    password:
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
      
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*_SQL.xml
  
api.gateway.url: http://localhost:8000

spring.jwt.secret: MSA
spring.jwt.access.header: Access-Token
spring.jwt.refresh.header: Refresh-Token

